// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMUzi8RgVWw0xUhVvJSHoGjGA9LnkPykc',
    appId: '1:465154488365:web:82b2c1cb132c60e364a0a4',
    messagingSenderId: '465154488365',
    projectId: 'mood-tracker-backend-dg',
    authDomain: 'mood-tracker-backend-dg.firebaseapp.com',
    storageBucket: 'mood-tracker-backend-dg.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6uTuuThuO1w7mPSH6S_8q7JN9Q2uODKw',
    appId: '1:465154488365:android:ead439395d66985b64a0a4',
    messagingSenderId: '465154488365',
    projectId: 'mood-tracker-backend-dg',
    storageBucket: 'mood-tracker-backend-dg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtGFk83SQeO4lzGIh0TLCPJEzHAo-qxVM',
    appId: '1:465154488365:ios:d971d7004ba0cdba64a0a4',
    messagingSenderId: '465154488365',
    projectId: 'mood-tracker-backend-dg',
    storageBucket: 'mood-tracker-backend-dg.firebasestorage.app',
    iosBundleId: 'com.example.movieTracker',
  );
}
